# Default values for devops-info-service-v2
replicaCount: 2

image:
  repository: morisummerz/devops-info-service
  tag: "latest"
  pullPolicy: Never

nameOverride: ""
fullnameOverride: ""

containerPort: 5000

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /health/
    port: 5000
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health/
    port: 5000
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3

env:
  - name: HOST
    value: "0.0.0.0"
  - name: PORT
    value: "5000"
  - name: DEBUG
    value: "true"
